# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Test
on:
  workflow_dispatch:
    inputs:
      upload-coverage:
        description: |
          Whether to upload test coverage artifacts.

          Defaults to `true`.
        type: boolean
        required: false
        default: true
      coverage-artifact-retention-days:
        description: |
          The number of days to retain uploaded test coverage artifacts for.

          Defaults to `0` which defaults to the number configured in the
          repository.
        type: number
        required: false
        default: 0
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      upload-coverage: ${{inputs.upload-coverage}}
      coverage-artifact-retention-days: ${{inputs.coverage-artifact-retention-days}}
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
