# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Build
on:
  workflow_dispatch:
    inputs:
      build-config:
        description: |
          The configuration to build for.

          Required input.

          Valid options are:

            * `development`
            * `production`
        type: string
        required: true
      upload-artifacts:
        description: |
          Whether to upload build artifacts.

          Defaults to `true`.
        type: boolean
        required: false
        default: true
      artifact-retention-days:
        description: |
          The number of days to retain uploaded artifacts for.

          Defaults to `0` which defaults to the number configured in the
          repository.
        type: number
        required: false
        default: 0
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      build-config: ${{inputs.build-config}}
      artifact-retention-days: ${{inputs.artifact-retention-days}}
      upload-artifacts: ${{inputs.upload-artifacts}}
