# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  workflow_call:
    inputs:
      upload-coverage:
        description: |
          Whether to upload test coverage artifacts.

          Defaults to `true`.
        type: boolean
        required: false
        default: true
      coverage-artifact-retention-days:
        description: |
          The number of days to retain uploaded test coverage artifacts for.

          Defaults to `0` which defaults to the number configured in the
          repository.
        type: number
        required: false
        default: 0
    secrets:
      github-token:
        description: |
          The token to use for making authenticated requests to GitHub APIs.
        required: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          lfs: true
      - id: setup-pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: install-dependencies
        name: Install dependencies
        run: pnpm install
      - id: install-playwright
        name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - id: test
        name: Test
        run: pnpm run test:ci
      - id: upload-artifacts
        name: Upload artifacts
        if: inputs.upload-coverage
        uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: ./coverage/
          if-no-files-found: warn
          retention-days: ${{inputs.coverage-artifact-retention-days}}
